// Generated by CoffeeScript 1.6.2
(function() {
  var ajax_fun, do_error, info, jsonp_num, play_episode, play_video, _i, _len, _ref,
    _this = this;

  play_episode = function(info) {
    return ajax_fun(info, null);
  };

  jsonp_num = 0;

  ajax_fun = function(info, video_data) {
    var poster_url, req_data, video_url;

    video_url = info.attr('href');
    poster_url = info.attr('poster');
    if (video_data) {
      req_data = {
        'video_url': video_url,
        'video_data': video_data
      };
    } else {
      req_data = {
        'video_url': video_url
      };
    }
    return $.ajax({
      url: "http://www.bungeer.com/video_url",
      type: 'POST',
      data: req_data
    }).error(function() {
      return do_error();
    }).done(function(res) {
      var fetch_url, fetch_url_data, jsonp_name, results, tag;

      video_url = info.attr('href');
      poster_url = info.attr('poster');
      res = JSON.parse(res);
      results = res['results'];
      fetch_url_data = results['fetch_url_data'];
      if (fetch_url_data) {
        jsonp_name = 'jsonp_' + jsonp_num++;
        window[jsonp_name] = function(res) {
          res = JSON.stringify(res);
          return ajax_fun(info, JSON.stringify({
            'tag': tag,
            'url_info': res
          }));
        };
        fetch_url = fetch_url_data['fetch_url'];
        tag = fetch_url_data['tag'];
        return $.ajax({
          url: fetch_url + jsonp_name,
          type: 'GET',
          dataType: 'jsonp',
          jsonp: false
        });
      } else {
        return play_video(info, res);
      }
    });
  };

  play_video = function(info, res) {
    var flv_url, height, m3u8_url, mp4_url, poster_url, result, url, url_high, vid, video_html, video_url, width;

    video_url = info.attr('href');
    poster_url = info.attr('poster');
    result = res['results'];
    url = result['url'];
    m3u8_url = result['m3u8_url'];
    vid = result['vid'];
    mp4_url = result['mp4_url'];
    flv_url = result['flv_url'];
    url_high = result["url_high"];
    poster_url = info.attr('poster');
    video_url = mp4_url;
    width = info.attr('width') || 640;
    height = info.attr('height') || 360;
    video_html = "<video id='' class='video-js vjs-default-skin' controls         preload='metadata' width='" + width + "' height='" + height + "' poster='" + poster_url + "'         data-setup='{}'        >         <source src='" + video_url + "' type='video/mp4'>        </video>        <link href='http://vjs.zencdn.net/4.2/video-js.css' rel='stylesheet'>        <script src='http://vjs.zencdn.net/4.2/video.js'></script>        ";
    info.append(video_html);
    info.css('margin-bottom', '20px');
    return $('.video-js').css('margin-bottom', 20);
  };

  do_error = function() {
    return console.log('error');
  };

  _ref = $('.bungeer_video_html5');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    info = _ref[_i];
    play_episode($(info));
  }

}).call(this);